CC = gcc

all : l3s1 l3s2 l3s3

CFLAGS = -D DEBUG

l3s1 : lab3step1.c
	    gcc $(CFLAGS) -o l3s1 lab3step1.c

l3s2 : lab3step2.c
	    gcc $(CFLAGS) -o l3s2 lab3step2.c 

l3s3 : lab3step3.c
	    gcc $(CFLAGS) -o l3s3 lab3step3.c 

clean: 
	rm l3s1 l3s2 l3s3
