CC = gcc

all : lab2step1 lab2step5

CFLAGS = -D DEBUG

lab2step1 : lab2step1.c
	    gcc $(CFLAGS) -o lab2step1 lab2step1.c

lab2step5 : lab2step5.c
	    gcc $(CFLAGS) -o lab2step5 lab2step5.c 

clean: 
	rm lab2step1 lab2step5
